#import "../lib.typ": *
= 输出生成 — 最后的 MLOG 文本
#labnote[ 第九站：格式化与集成 ]

MLOG 指令序列已经有了。现在要把它变成用户可以使用的形式——一个 `&str` 字符串字面量。

== 生成最终的字符串

```rust
// codegen.rs
pub fn generate_mlog(instrs: &[IrInstr]) -> String {
    let mut out = String::new();
    for instr in instrs {
        match instr {
            IrInstr::Set { result, value } => {
                out.push_str(&format!("set {} {}\n", result, fmt_value(value)));
            }
            IrInstr::Op { opcode, result, lhs, rhs } => {
                out.push_str(&format!("op {} {} {} {}\n",
                    opcode, result, fmt_value(lhs), fmt_value(rhs)));
            }
            IrInstr::Jump { label } => {
                out.push_str(&format!("jump {} always\n", label));
            }
            IrInstr::JumpIf { label, condition, lhs, rhs } => {
                out.push_str(&format!("jump {} {} {} {}\n",
                    label, condition, fmt_value(lhs), fmt_value(rhs)));
            }
            IrInstr::Label(name) => {
                out.push_str(&format!(":{}\n", name));
            }
            IrInstr::Print(val) => {
                out.push_str(&format!("print {}\n", fmt_value(val)));
            }
            IrInstr::PrintFlush(block) => {
                out.push_str(&format!("printflush {}\n", block));
            }
            // ... 其他指令
        }
    }
    out
}
```

输出是纯文本 MLOG——每个指令一行。

== 可选：添加注释

```rust
// 可选：在生成的 MLOG 中添加注释
fn generate_with_comments(ir: &IrProgram, source: &str) -> String {
    let mut out = String::new();
    out.push_str("# Generated by rust2mlog\n");
    out.push_str(&format!("# Source:\n"));
    for line in source.lines() {
        out.push_str(&format!("#   {}\n", line));
    }
    out.push('\n');
    out.push_str(&generate_mlog(&ir.instrs));
    out
}
```

MLOG 中 `#` 开头的行是注释。添加注释有助于调试——可以看到原始 DSL 和生成的 MLOG 的对应关系。

== 回到 macro 入口

最终的宏入口将 MLOG 文本返回为 Rust 字符串字面量：

```rust
#[proc_macro]
pub fn mlog(input: TokenStream) -> TokenStream {
    let input_ts: proc_macro2::TokenStream = input.into();

    let program = match parser::parse_program(input_ts.clone()) {
        Ok(ast) => ast,
        Err(err) => return err.to_compile_error().into(),
    };

    let ir = ir::lower_program(&program);
    let mlog_text = codegen::generate_mlog(&ir.instrs);

    // 关键：把 MLOG 文本包裹为 Rust 字符串字面量
    let output = quote::quote! { #mlog_text };
    output.into()
}
```

#concept[
  `quote! { #mlog_text }` 中 `mlog_text` 是 `String`。quote 会把它展开为字符串字面量。

  ```rust
  // 宏展开前
  let program = mlog! { set x 5 };

  // 宏展开后（由 proc macro 生成）
  let program = "set x 5\n";
  ```

  program 的类型是 `&'static str`——编译时确定，零运行时开销。
]

== 用户如何使用生成的 MLOG

=== 直接嵌入

```rust
const MY_PROGRAM: &str = mlog! {
    let mut i = 0;
    while i < 10 {
        print(i);
        i += 1;
    }
};

fn main() {
    println!("MLOG program:\n{}", MY_PROGRAM);
    // 复制到 Mindustry 处理器
}
```

=== 写入文件

```rust
use std::fs;

fn main() {
    let mlog = mlog! {
        ubind(@poly);
        ucontrol move 100 200 0 0 0;
    };
    fs::write("my_program.mlog", mlog).unwrap();
}
```

=== 配合 build.rs 生成输出文件

在 `build.rs` 中不能直接用 proc macro，但可以：

```rust
// build.rs — 生成包含 MLOG 的常量
fn main() {
    // 生成一个 .rs 文件，其中包含 MLOG 常量
    let mlog_code = include_str!("my_program.mlog");
    // ...
}
```

== 格式化细节

MLOG 对格式不敏感——最重要的是换行。但好的格式有助于调试：

```
# 好的格式
set x 5
op add x x 1
jump loop equal x 10

# 也能工作，但调试麻烦
set x 5
op add x x 1
jump loop equal x 10
```

我们选择简洁格式——每条指令一行，无多余缩进。标签独占一行。

== 小结

- 代码生成的最终输出是 `String`
- 宏把 `String` 展开为 `&'static str` 字面量
- 可选添加注释以帮助调试
- 用户可以用 `const`、文件写入等方式使用生成的 MLOG
- MLOG 文本是纯文本——可以被任何工具链消费
- 编译时生成 = 零运行时开销
#pagebreak()
